######################################################################
# Automatically generated by qmake (3.1) Sun Jun 21 22:16:39 2020
######################################################################

TEMPLATE = app
TARGET = test3d
INCLUDEPATH += .

QT += widgets gui core

# The following define makes your compiler warn you if you use any
# feature of Qt which has been marked as deprecated (the exact warnings
# depend on your compiler). Please consult the documentation of the
# deprecated API in order to know how to port your code away from it.
DEFINES += QT_DEPRECATED_WARNINGS

# You can also make your code fail to compile if you use deprecated APIs.
# In order to do so, uncomment the following line.
# You can also select to disable deprecated APIs only up to a certain version of Qt.
#DEFINES += QT_DISABLE_DEPRECATED_BEFORE=0x060000    # disables all the APIs deprecated before Qt 6.0.0

# Input
HEADERS += Test3D.h \
           3d/Camera.h \
           3d/Image3D.h \
           3d/PixelInfo.h \
           3d/Shape3D.h \
           3d/Vector3D.h
SOURCES += Test3D.cpp \
           3d/Camera.cpp \
           3d/Image3D.cpp \
           3d/PixelInfo.cpp \
           3d/Shape3D.cpp \
           3d/Vector3D.cpp
